apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: sample-app
  namespace: flux-system
spec:
  interval: 30s
  url: oci://zot:5000/demo/myapp-manifests
  insecure: true
  ref:
    tag: latest
