storage:
  type: sqlite
  path: /data/data.db
ui:
  header: Khue Doan
endpoints:
  - name: blog
    group: apps
    url: "https://khuedoan.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
  - name: homelab-docs
    group: apps
    url: "https://homelab.khuedoan.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
  - name: draw
    group: apps
    url: "https://draw.khuedoan.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
  - name: headscale
    group: platform
    url: "https://headscale.khuedoan.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  # Quis custodiet ipsos custodes?
  # Same config, different datacenter
  - name: status
    group: platform
    url: "https://status.khuedoan.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
  - name: status-2
    group: platform
    url: "https://status-2.khuedoan.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
  - name: status-3
    group: platform
    url: "https://status-3.khuedoan.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
