apiVersion: fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata:
  name: cert-manager
  annotations:
    config.kubernetes.io/function: |
      container:
        network: true
        image: gcr.io/kpt-fn/render-helm-chart:unstable
        mounts:
          - type: bind
            src: ./values.yaml
            dst: /tmp/values.yaml
helmCharts:
  - chartArgs:
      name: cert-manager
      version: v1.11.3
      repo: https://charts.jetstack.io
    templateOptions:
      namespace: cert-manager
      releaseName: cert-manager
      values:
        valuesFiles:
          - tmp/values.yaml
