apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blogposts.stable.khuedoan.com
spec:
  group: stable.khuedoan.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                content:
                  type: string
  scope: Namespaced
  names:
    plural: blogposts
    singular: blogpost
    kind: BlogPost
    shortNames:
    - bp
