kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onedev
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: onedev
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: onedev
  apiGroup: rbac.authorization.k8s.io
