apiVersion: apps/v1
kind: Deployment
metadata:
  name: onedev
  labels:
    tier: server
spec:
  selector:
    matchLabels:
      tier: server
  strategy:
    type: Recreate
  template:
    metadata:
      name: onedev
      labels:
        tier: server
    spec:
      containers:
      - name: onedev
        image: 1dev/server
        volumeMounts:
        - mountPath: "/opt/onedev"
          name: onedev
        ports:
        - containerPort: 6610
        - containerPort: 6611
        env:
        - name: hibernate_dialect
          value: org.hibernate.dialect.MySQL5InnoDBDialect
        - name: hibernate_connection_driver_class
          value: com.mysql.cj.jdbc.Driver
        - name: hibernate_connection_url
          value: jdbc:mysql://mysql:3306/onedev?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
        - name: hibernate_connection_username
          value: root
        - name: hibernate_connection_password
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        - name: hibernate_hikari_maximumPoolSize
          value: "25"
      initContainers:
      - name: init
        image: busybox
        command: ["sh", "-c", "until nslookup mysql.onedev.svc.cluster.local; do echo waiting for mysql; sleep 2; done;"]
      volumes:
      - name: onedev
        persistentVolumeClaim:
          claimName: onedev
      serviceAccountName: onedev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
  labels:
    tier: database
spec:
  selector:
    matchLabels:
      tier: database
  strategy: 
    type: Recreate
  template:
    metadata:
      name: mysql
      labels:
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        args:
        - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_DATABASE
          value: onedev
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        readinessProbe:
          exec:
            command:
            - bash 
            - "-c" 
            - | 
              mysql -uroot -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql