apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onedev
  namespace: {{ .Release.Namespace }}
  labels:
    tier: server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
  labels:
    tier: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
