version: '3'

services:
  minio:
    image: quay.io/minio/minio
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=testing123
    ports:
      - 9000:9000
      - 9090:9090
    command: server /data --console-address ":9090"
