name: Nix

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on:
      - gha-runner-khuedoan-playground
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: echo hello
      - run: nix develop --command kpt version
