name: Nix

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on:
      - self-hosted
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop --command kpt version
